# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bestLogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_pic', smartfields.fields.ImageField(upload_to='imageApp/images/products/')),
                ('model_jpeg', smartfields.fields.ImageField(upload_to='imageApp/images/products/')),
                ('add', models.ManyToManyField(related_name='users_cart', to='bestLogin.User')),
                ('likes', models.ManyToManyField(related_name='users_likes', to='bestLogin.User')),
            ],
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avg_rating', models.ManyToManyField(related_name='users_ratings', to='bestLogin.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestLogin.User')),
            ],
        ),
    ]
